#!/usr/bin/env php

<?php

require __DIR__ . '/config.php';
require __DIR__ . '/vendor/autoload.php';

use Vortex\Console\CreateVhostCommand;
use Symfony\Component\Console\Application;

$app = new Application('Developer Toolbox', 1.0);
$app->add(new CreateVhostCommand);
$app->run();
